resilience4j:
  retry:
    instances:
      compra-fornecedor:
        max-attempts: '3'
        wait-duration: 2s
        enable-exponential-backoff: 'true'
  ratelimiter:
    instances:
      max-rate:
        limit-refresh-period: 10s
        limit-for-period: 100
  bulkhead:
    instances:
      default:
        max-concurrent-calls: '100'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: 'true'
    register-with-eureka: 'true'
spring:
  application:
    name: loja
server:
  servlet:
    context-path: /loja
